module.exports = {
	CREATE_ROOM: 'create room',
	JOIN_ROOM: 'join room',
	ROOM_ID: 'room id',
	ROOM_FULL: 'room full',
	PLAYER_LEFT: 'player left',
	NEW_PLAYER: 'new player',
	SUCCESSFUL_JOIN: 'successful join',
	FAILED_JOIN: 'failed join',
	REMOVE_MOVIE: 'remove movie',
	DID_REMOVE_MOVIE: 'did remove movie',
	ADD_MOVIE_STARTER_PACK: 'add movie starter pack',
	DID_ADD_MOVIE_PACK: 'did add movie pack',
	ADD_MOVIE: 'add movie',
	DID_ADD_MOVIE: 'did add movie',
	ADD_MOVIE_ERROR: 'add movie error',
};
