module.exports = {
	CREATE_ROOM: 'create room',
	START_GAME: 'start game',
	DID_START_GAME: 'did start game',
	GAME_IN_PROGRESS: 'game in progress',
	JOIN_ROOM: 'join room',
	ROOM_ID: 'room id',
	ROOM_FULL: 'room full',
	PLAYER_LEFT: 'player left',
	NEW_PLAYER: 'new player',
	SUCCESSFUL_JOIN: 'successful join',
	FAILED_JOIN: 'failed join',
	REMOVE_MOVIE: 'remove movie',
	DID_REMOVE_MOVIE: 'did remove movie',
	ADD_MOVIE_STARTER_PACK: 'add movie starter pack',
	DID_ADD_MOVIE_PACK: 'did add movie pack',
	ADD_MOVIE: 'add movie',
	DID_ADD_MOVIE: 'did add movie',
	ADD_MOVIE_ERROR: 'add movie error',

	PLAYER_SUBMITTED_GUESS: 'player submitted guess',
	PLAYER_DID_SUBMIT_GUESS: 'player did submit guess',
	DID_SCORE_ROUND: 'did score round',
};
