export default [
	{
		image: 'https://resizing.flixster.com/ZHR_OubfrDf7bZugw3ZJW8OdBqE=/fit-in/80x80/v1.bTsxMTE2NjcyNTtqOzE3OTQ5OzEyMDA7ODAwOzEyMDA',
		meterClass: 'certified_fresh',
		meterScore: 86,
		name: 'Inception',
		subline: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, ',
		url: '/m/inception',
		year: 2010,
	},
	{
		image: 'https://resizing.flixster.com/Rp6sStTJiMw8XNStyr4EAolounw=/fit-in/80x80/v1.bTsxMTE3MTcwMjtqOzE3OTQ5OzEyMDA7ODAwOzEyMDA',
		meterClass: 'certified_fresh',
		meterScore: 86,
		name: 'Django Unchained',
		subline: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, ',
		url: '/m/django_unchained_2012',
		year: 2012,
	},
	{
		image: 'https://resizing.flixster.com/gCDXT8Xqqcb0M-HiRP-QrcTRFXo=/fit-in/80x80/v1.bTsxMTE2NjMyMDtqOzE3OTQ5OzEyMDA7ODAwOzExOTM',
		meterClass: 'certified_fresh',
		meterScore: 89,
		name: 'Titanic',
		subline: 'Leonardo DiCaprio, Kate Winslet, Billy Zane, ',
		url: '/m/titanic',
		year: 1997,
	},
	{
		image: 'https://resizing.flixster.com/PQWf5Sfu138qg6wRBqq6V5n2ehU=/fit-in/80x80/v1.bTsxMTE3MjU4ODtqOzE3OTQ5OzEyMDA7ODAwOzEyMDA',
		meterClass: 'rotten',
		meterScore: 49,
		name: 'The Great Gatsby',
		subline: 'Leonardo DiCaprio, Carey Mulligan, Tobey Maguire, ',
		url: '/m/the_great_gatsby_2013',
		year: 2013,
	},
	{
		image: 'https://resizing.flixster.com/2bpD7tSC42lbp2uztpwGOvwPklI=/fit-in/80x80/v1.bTsxMTE3Njk3NjtqOzE3OTQ5OzEyMDA7ODAwOzEyMDA',
		meterClass: 'certified_fresh',
		meterScore: 78,
		name: 'The Wolf of Wall Street',
		subline: 'Leonardo DiCaprio, Jonah Hill, Margot Robbie, ',
		url: '/m/the_wolf_of_wall_street_2013',
		year: 2013,
	},
];
