export default [
	{
		image: 'https://resizing.flixster.com/TcX26-3i1x9g_Q_noyA_ysktj1A=/fit-in/80x80/v1.bTsxMTIwNzI0MTtqOzE3OTQ5OzEyMDA7MTgwMDsyNDAw',
		meterClass: 'rotten',
		meterScore: 47,
		name: 'The Princess Diaries',
		subline: 'Julie Andrews, Anne Hathaway, Hector Elizondo, ',
		url: '/m/princess_diaries',
		year: 2001,
	},
	{
		image: 'https://resizing.flixster.com/5oWoziTAY3hIJY21DPGIHqfGwUQ=/fit-in/80x80/v1.bTsxMTIwNzI3NjtqOzE3OTQ5OzEyMDA7MTk5ODsyNjY0',
		meterClass: 'certified_fresh',
		meterScore: 86,
		name: 'Mulan',
		subline: 'Ming-Na Wen, Eddie Murphy, Lea Salonga, ',
		url: '/m/mulan',
		year: 1998,
	},
	{
		image: 'https://resizing.flixster.com/iPhTSSox7yeHUD8VGtdmaSquHvU=/fit-in/80x80/v1.bTsxMTIwNDExNTtqOzE3OTQ5OzEyMDA7MTIwMDsxNjAw',
		meterClass: 'certified_fresh',
		meterScore: 88,
		name: 'Shrek',
		subline: 'Mike Myers, Eddie Murphy, Cameron Diaz, ',
		url: '/m/shrek',
		year: 2001,
	},
	{
		image: 'https://resizing.flixster.com/P1Nivj4y2_3nzTCnNN0-dsYqkBo=/fit-in/80x80/v1.bTsxMTIwNzEzMztqOzE3OTQ5OzEyMDA7MjI1MDszMDAw',
		meterClass: 'certified_fresh',
		meterScore: 94,
		name: 'Aladdin',
		subline: 'Scott Weinger, Robin Williams, Linda Larkin, ',
		url: '/m/1042582-aladdin',
		year: 1992,
	},
	{
		image: 'https://resizing.flixster.com/Q-iiO-PDBvuGV8EBL6ykNgdjlzM=/fit-in/80x80/v1.bTsxMTE3MzU4NDtqOzE3OTQ5OzEyMDA7MjE2NzszMjEw',
		meterClass: 'certified_fresh',
		meterScore: 90,
		name: 'Frozen',
		subline: 'Kristen Bell, Idina Menzel, Jonathan Groff, ',
		url: '/m/frozen_2013',
		year: 2013,
	},
];
