export default [
	{
		image: 'https://resizing.flixster.com/A31QtxjB2dTh0__osCvH6XfREHo=/fit-in/80x80/v1.bTsxMTE2NzgzNTtqOzE3OTQ5OzEyMDA7ODAwOzEyMDA',
		meterClass: 'certified_fresh',
		meterScore: 87,
		name: 'The Dark Knight Rises',
		subline: 'Christian Bale, Michael Caine, Gary Oldman, ',
		url: '/m/the_dark_knight_rises',
		year: 2012,
	},
	{
		image: 'https://resizing.flixster.com/Trz-UotpHy5oV_Wz_xzK1T4LDSY=/fit-in/80x80/v1.bTsxMTY5MDA3MDtwOzE3ODY1OzEyMDA7NDg4OzcyMA',
		meterClass: 'certified_fresh',
		meterScore: 91,
		name: 'Captain America: Civil War',
		subline: 'Chris Evans, Robert Downey Jr., Scarlett Johansson, ',
		url: '/m/captain_america_civil_war',
		year: 2016,
	},
	{
		image: 'https://resizing.flixster.com/ZRHRksmn4fZhDogUa5HeyY9zCvQ=/fit-in/80x80/v1.bTsxMTQyMDkxNDtqOzE3OTUyOzEyMDA7MTAwMDsxNDgw',
		meterClass: 'certified_fresh',
		meterScore: 84,
		name: 'Deadpool',
		subline: 'Ryan Reynolds, Morena Baccarin, Ed Skrein, ',
		url: '/m/deadpool',
		year: 2016,
	},
	{
		image: 'https://resizing.flixster.com/vr_mQTuNpz7N5q5iedTt3aMWhEU=/fit-in/80x80/v1.bTsxMTk0OTYxMDtqOzE3OTEzOzEyMDA7MjAyNTszMDAw',
		meterClass: 'rotten',
		meterScore: 48,
		name: 'X-Men: Apocalypse',
		subline: 'James McAvoy, Michael Fassbender, Jennifer Lawrence, ',
		url: '/m/x_men_apocalypse',
		year: 2016,
	},
	{
		image: 'https://resizing.flixster.com/rzYLEUnLaNlPiPbzsFzkNW9_jWk=/fit-in/80x80/v1.bTsxMTE3ODA4MjtqOzE3OTQ5OzEyMDA7MTY4ODsyNTAw',
		meterClass: 'certified_fresh',
		meterScore: 91,
		name: 'Guardians of the Galaxy',
		subline: 'Chris Pratt, Zoe Saldana, Dave Bautista, ',
		url: '/m/guardians_of_the_galaxy',
		year: 2014,
	},
];
